// example/react/vite-project/src/hooktest.tsx
import { createReactParamsHook } from "../../../../dist";
import { searchrouter } from "./searchrouter";
import { useEffect, useState } from "react";
import React from "react";
const useParams = createReactParamsHook({
    router: searchrouter,
    useEffect,
    useState,
});
export default function Hooktest() {
    const params = useParams();
    useEffect(() => {
        console.log(params);
    }, [params]);
    return <div>params:{JSON.stringify(params)}</div>;
}

// example/vue/my-vue-app/src/hooktest.vue
<template>
    <div>params:{{ JSON.stringify(params) }}</div>
</template>
<script lang="ts">
import {
    defineComponent,
    ref,
    readonly,
    onMounted,
    onUnmounted,
    watch,
} from "vue";
import { createVueParamsHook } from "../../../../dist";
import { hashrouter } from "./hashrouter";
const useParams = createVueParamsHook({
    router: hashrouter,
    ref,
    readonly,
    onMounted,
    onUnmounted,
});
export default defineComponent({
    setup() {
        const params = useParams();
        watch(
            () => params.value,
            (params) => {
                console.log(params);
            }
        );
        return { params };
    },
});
</script>
